sudo: required
services: 
  - docker

before_install:
  - docker build -t juanjbon/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true juanjbon/react-test npm test -- --coverage

after_success:
  - docker build -t juanjbon/multi-client ./client
  - docker build -t juanjbon/multi-nginx ./nginx
  - docker build -t juanjbon/multi-server ./server
  - docker build -t juanjbon/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push juanjbon/multi-client
  - docker push juanjbon/multi-server
  - docker push juanjbon/multi-nginx
  - docker push juanjbon/multi-worker 
